### ISSUE TITLE
Displays are not recognized

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/startdde#10]
Using Arch on Dell XPS-13 with a docking station.

I have three monitors and have them configured using the DDE-Settings.
If I deconnect the Notebook from the station and reconnect, it won't switch to three monitors again. It does not even show the configuration, as if they were not recognized.

I can make them main display one after another, so they kinda "wake up". Then I get The possibility to choose the saved config again.
Or I just reboot, so everything is reconized and configured automaticly.

Really annoying.

**Comment by jouyouyun** [comment]
Please paste the outputs `xrandr --verbose` and upload the file `/var/log/Xorg.0.log` when your three display not recognized!
Thanks!

**Comment by DasJott** [comment]
Here they are. I made a zip includeing what you requested.
Additionaly I added the display.json where you can see the settings I saved. None of them are displayed when the error occurres. This is why there are so many new ones..

I just have to disconnect the docking-station and reconnect it. Monitors won't be switched to as usual and options are not chosable.

[logs.zip](https://github.com/linuxdeepin/startdde/files/1967476/logs.zip)

**Comment by jouyouyun** [comment]
From your log, i found `eDP1`, `DP1-1` and `DP1-2` connected, is right?
Does your notebook power supply meet three monitors?

**Comment by DasJott** [comment]
Yes it is a Dell XPS-13 connected to its docking station.
The monitors and the network and everything is connected to that docking station, while the station is connected via USB-C to the laptop.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
