### ISSUE TITLE
White Screen of "Death"!!!!

### ISSUE THREAD

**Issue by keeganmilsten** [linuxdeepin/startdde#11]
Hi there! I am one of the main developers of Reborn OS, a distro founded with Deepin in mind. We offer all our users the option to install your desktop environment through Cnchi (we're Arch based) and so far it has been wonderful! However, for the past few days, our users have been reporting problems. I tested it in Virtualbox, and sadly I can testify that this is indeed an issue - no matter what login manager I use. Anyways, I'll get to the point. After one installs Deepin (installing all packages in the groups `deepin` and `deepin-extra` from Arch Linux) and boots up into their newly installed system for the first time in a VM, they get to the login screen. All's good so far, right? Well, there goes our happy little world. Upon entering in your user password and hitting Enter, it begins to log in and everything turns white. The screen goes completely white, and only the cursor is visible. No dock, no anything. Just a stark white screen and a cursor. Here's a screenshot:
![](https://cdn.pbrd.co/images/HmTmxHy.png)

Thanks to our amazing testers, we at Reborn have been working hard to figure out what is causing this, but to no avail. Hopefully, you can shed some light on the issue and people can give Deepin a go in a Vm once again!

NOTE: This is happening in ALL VMs of post-install Arch sytems. Antergos, us (Reborn), and even Arch itself. As such, this really is bigger than just one distro.

**Comment by keeganmilsten** [comment]
Same here. Thankfully, this seems to only be effecting Deepin in virtual machines.Due to this, when Deepin is installed on real hardware, it should still work like a charm. But we all know that most people like to try things out in VMs first, and this would NOT give a good impression! As such, we hope to see this solved asap.

**Comment by jouyouyun** [comment]
@keeganmilsten `echo "dbus-launch startdde" > ~/.xinitrc` then exec `startx` in tty, is it normally?

**Comment by keeganmilsten** [comment]
While an great idea, it sadly gave me that same white screen of "death". But sticking that piece of code in was a good idea! Just wish it had been able to help us narrow things down a bit more.

P.S. Thank you SO much for trying to help @jouyouyun. It is highly appreciated, and is one of the things I love about Deepin - how willing you guys are to help. So thanks again!

**Comment by jouyouyun** [comment]
@keeganmilsten create a file `startdde.sh`, the contents is:
```shell
#!/bin/bash
env DDE_DEBUG_LEVEL="debug" /usr/bin/startdde.orig > /tmp/dde.log 2>&1
```

Then exec the following commands:
```shell
chmod +x startdde.sh
sudo cp /usr/bin/startdde /usr/bin/startdde.orig
sudo cp startdde.sh /usr/bin/startdde
```
Then login and upload the log file `/tmp/dde.log`, thanks!

**Comment by keeganmilsten** [comment]
Thank you so much! I'm heading off to bed here (tricky timezone thing) but I'll do that first thing in the morning!

Once again, I cannot properly express how much I appreciate your help. Thank you.

**Comment by keeganmilsten** [comment]
> Then login and upload the log file /tmp/dde.log, thanks!

Since I am using a VM, I cannot log in and then toggle to a tty. If I do, that action gets run outside the VM as well. Due to this, I don't know if I can effectively get that log file to you. Would you know of a workaround?

Thanks!

**Comment by jouyouyun** [comment]
@keeganmilsten ssh?

**Comment by keeganmilsten** [comment]
Thanks for the tip! Here's the uploaded file:
[dde.log](https://github.com/linuxdeepin/startdde/files/2051937/dde.log)

**Comment by keeganmilsten** [comment]
If you would prefer not to download the file, here's its contents:
```
libGL error: pci id for fd 23: 80ee:beef, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
<debug> vm.go:45: launchWindowManager in VM
```

**Comment by keeganmilsten** [comment]
So it seems that basically, it just cannot load the driver. My guess is that could be due to a recent update in Virtualbox (got one about a week ago) in which they may have changed how their driver works?

**Comment by jouyouyun** [comment]
Try install virtualbox x driver in virtual machine, install `virtualbox-guest-additions-iso` on host machine, and reboot the virtual machine to install the additions.

**Comment by keeganmilsten** [comment]
Yay!!! Thank you SO MUCH @jouyouyun! I'll be sure to do that. 

Once again, I would like to sincerely thank you and the rest of Deepin. You guys are absolutely amazing! I wish you the best, and (hopefully) won't bog you down with any more issues in the near future. 

God bless, and good luck!

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
