### ISSUE TITLE
DDE用go写，DDE UI 层为什么不用go写呢？

### ISSUE THREAD

**Issue by goodforever** [linuxdeepin/startdde#12]
DDE用go写，DDE UI 层为什么不用go写呢？

**Comment by wszqkzqk** [comment]
go的图形库不完善

**Comment by goodforever** [comment]
@wszqkzqk 图形库除了go写DDE，还有别的非go写的与DDE同层的图形库？

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
