### ISSUE TITLE
Display scale is set on start at 200%!

### ISSUE THREAD

**Issue by FredBezies** [linuxdeepin/startdde#13]
I noticed this bug recently, while testing a Deepin installation on an Archlinux in a Virtualbox Machine.

Before this commit https://github.com/linuxdeepin/startdde/commit/89e6ec70badd2ae19802f617612b942f048d56f7 display scale was set to 100%

I revert this display bug in control center setting display scale at 100%.

I also opened a bug on archlinux tracker: https://bugs.archlinux.org/task/59461

**Comment by jouyouyun** [comment]
@electricface why?

**Comment by electricface** [comment]
应该是虚拟机里面工作不正常

**Comment by FredBezies** [comment]
Looks like a bad resolution "sniffing".

Here is a full screen size screenshot. You'll see resolution on my 19 inch screen is not 1366x768 but 1360x768. Can be related?

![full-screen](https://user-images.githubusercontent.com/8571419/43380873-f9876be0-93d2-11e8-9994-1e6e225a2162.png)

Hope it helps.

**Comment by FredBezies** [comment]
It is fixed. Just verified 2 minutes ago! Thanks a lot.
