### ISSUE TITLE
What is /usr/lib/UIAppSched.hooks?

### ISSUE THREAD

**Issue by romildo** [linuxdeepin/startdde#14]
When running DDE I see the following message

```
startmanager.go:91: open /usr/lib/UIAppSched.hooks/launched: no such file or directory
```

What is `/usr/lib/UIAppSched.hooks/launched` supposed to be?

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
