### ISSUE TITLE
Crash in startdde after started for ~20s

### ISSUE THREAD

**Issue by fasheng** [linuxdeepin/startdde#2]
<a href="https://github.com/felixonmars"><img src="https://avatars.githubusercontent.com/u/1006477?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by @felixonmars**
_Wednesday Jan 06, 2016 at 12:44 GMT_
_Originally opened as https://github.com/fasheng/arch-deepin/issues/222_

---

It actually looks very strange to me, and I am not sure if this helps...

```
Jan 06 20:32:00 flygon.felixc.at systemd-coredump[13676]: Process 6021 (startdde) of user 1000 dumped core.

                                                          Stack trace of thread 6583:
                                                          #0  0x00007f5be3d6ee15 _nv014tls (libnvidia-tls.so.358.16)
                                                          #1  0x00007f5be606c088 n/a (libGL.so.1)
                                                          #2  0x00007f5be60af365 n/a (libGL.so.1)
                                                          #3  0x00007f5beecb5885 n/a (n/a)
```

**Comment by jouyouyun** [comment]
@felixonmars can this bug reproduce?

**Comment by felixonmars** [comment]
I don't think so, closing for now.
