### ISSUE TITLE
[Archlinux] Crash ?

### ISSUE THREAD

**Issue by funilrys** [linuxdeepin/startdde#4]
Hello,
Here you can get the output of startdde.

My questions are:
Is it normal ? 
What mistakes did I do ?

Indeed I was searching why does my login screen doesn't look like the normal deepin login screen I had on my other computers ... And i tried to manually start `startdde` ...

Thanks in advance for your help.
Thanks for your work !

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x80 pc=0x640160]

goroutine 1 [running]:
panic(0x8bf460, 0xc82000a0f0)
	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/BurntSushi/xgb/xproto.InternAtom(0x0, 0x30000, 0x94db18, 0x3, 0x0)
	/build/startdde/src/build/src/github.com/BurntSushi/xgb/xproto/xproto.go:10975 +0x300
pkg.deepin.io/dde/startdde/display.getAtom(0x0, 0x94db18, 0x3, 0x9a8e20)
	/build/startdde/src/startdde/gopath/src/pkg.deepin.io/dde/startdde/display/utils.go:67 +0x3f
pkg.deepin.io/dde/startdde/display.init()
	/build/startdde/src/startdde/gopath/src/pkg.deepin.io/dde/startdde/display/detect_output.go:144 +0x176
main.init()
	_/build/startdde/src/startdde/_obj/_cgo_import.go:1 +0x47
```

[startdde.txt](https://github.com/linuxdeepin/startdde/files/384682/startdde.txt)

**Comment by fasheng** [comment]
> Indeed I was searching why does my login screen doesn't look like the normal deepin login screen I had on my other computers ... 

Login screen? You mean lightdm greeter scrren? You could force to use lightdm-deepin-greeter by editing `/etc/lightdm/lightdm.conf`
```
[SeatDefaults]
greeter-session=lightdm-deepin-greeter
```

> And i tried to manually start startdde ...

If you want to start DDE from tty, please use the **xinit** as a wrapper

1. edit ~/.xinitrc

    ```
    exec startdde
   ```
2. run `xinit`

https://wiki.archlinux.org/index.php/Deepin_Desktop_Environment

**Comment by funilrys** [comment]
Thank you for your answer, 
I had written  `lightdm-deepin-greetr` insteed of `lightdm-deepin-greeter`
