### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by ceyhunnabiyev** [linuxdeepin/startdde#5]
Most of linux  desktop  environments use Wayland default, because this is more secure and faster than Xorg..   

Do you have full Wayland support, if yes how run it ??

**Comment by manateelazycat** [comment]
Wayland still have many problem on Nvidia video card, we won't switch to wayland until it fixed those problem.

Thanks for your suggestion!

**Comment by ceyhunnabiyev** [comment]
I understand, thanks for your answer!!

**Comment by sebasmagri** [comment]
Is there a chance to re-open this now? I'm having a bunch of issues now with Xorg on fedora and would like to see if it's possible to make startdde use wayland. Probably we could enable an additional non-default xsession so that users can try it?
