### ISSUE TITLE
USB device connection issues

### ISSUE THREAD

**Issue by ceyhunnabiyev** [linuxdeepin/startdde#6]
1. When I plug-in new USB flash drive,  computer:/// (show all connected storage devices) is opened, automount is working, but not showing  containing folder of USB drive on startup...
2. When I eject USB flash drive,  Deepin  unmounts it , but doesn't unpower  USB drive

Can you please fix these issues ? If not, how can  I disable automount option in Deepin DE??

**Comment by jouyouyun** [comment]
The problem 1 is the design of this; the second does not understand your meaning, trouble to say more details

**Comment by ceyhunnabiyev** [comment]
Hi, @jouyouyun 
1. When I plug-in new USB flash drive, it shows me Nautilus pop-up window with computer:///... It doesn't  matter which file-manager to use . The result is same:
![screenshot from 2017-02-14 14 32 52](https://cloud.githubusercontent.com/assets/5506156/22926014/4b4544a4-f2c4-11e6-8209-c2aecb57c9e9.png)

2. Deepin dde-dock  doesnt have  usb eject functionality, only unmounts it. **Unpower** details: 
My USB drive has light on,  when I plug-in this. I want to unmount this  from  dde-dock , but it doesnt turn off light on USB drive, but   Nautilus  eject turns off it. This reason may cause usb drive damage, when it is unpluged..  

---------------------------------------------------------------------------------
Thanks for attention to my questions!!!     
Sorry for my poor English, While I find new issues, or suggestions, I  will share with you, because  you have great  work!!! 
Regards
