### ISSUE TITLE
Bug: startx starts a process `adduser cocoa sambashare` which eats up the CPU

### ISSUE THREAD

**Issue by cocoa1231** [linuxdeepin/startdde#7]
I am on Arch Linux, and I thought I'd give deepin desktop environment a shot, and I noticed that it ate up all of my CPU as soon as I typed in startx. After digging a bit, I found out that it was trying to add my user to the sambashare group, which is weird becaues I explicitly removed samba from my computer. 

This is unusual behaviour which I'd like to see get patched in the next update. Please ask for any other information which you may require

**Comment by jouyouyun** [comment]
Try `echo 'dbus-launch startdde' > ~/.xinitrc` then startx again.

**Comment by jouyouyun** [comment]
startdde no called `useradd` command

**Comment by jouyouyun** [comment]
No responsed. But the bug maybe cause by deepin file manager, closed!
