### ISSUE TITLE
判断DRI的方法有问题，导致来回切换nvidia/nouveau驱动会导致窗口特效切换失效

### ISSUE THREAD

**Issue by palxex** [linuxdeepin/startdde#74]
之前用deepin 15.11时触发过此问题，当时以为是使用nvidia官方驱动破坏了关键文件，未提交。
这两天因为个人原因换到了manjaro-deepin-18.0.2，使用mhwd来回切换后又出现了此问题。

重现方法：（不保证100%，但我两次应该都是这么触发的）
1. 安装时使用nonfree驱动
2. 换成nouveau驱动，重启
3. 换回nvidia驱动，重启
4. 启动进桌面，OSD提示窗口特效已关闭，毛玻璃效果确实没有，打开deepin设置——显示，这里的特效提示按钮却是开，点击按钮关闭，OSD提示已关闭但特效提示按钮仍为开。
5. 手动执行deepin-wm --replace，毛玻璃特效正常，但下次启动进来仍同4。

分析：根据5的表现，判断deepin-wm并无问题，问题应属于调度它的代码。根据线索顺藤摸瓜找到startdde的supportRunGoodWM，其会调用isDriverLoadedCorrectly，而后者是根据Xorg.0.log里的字句判断DRI是否启动的（direct rendering: DRI\\d+ enabled，因为是正则无论DRI2还是3都能匹配）。这下真相大白，这句我最后的驱动下恰恰没有，只有几句类似NVIDIA(0): [DRI2] Setup complete的……但是实际上通过glxinfo获得的信息是DRI是开了的。
现在不清楚的问题就是原先manjaro-deepin默认安装是怎么获得的这句log。但是无论如何，从log里寻章摘句我觉得相当不保险。

之所以最后选定官方闭源驱动原因是经过多次对比最终确定nouveau是我机器在linux下时不时死机的根源（无论deepin还是manjaro），不过这个是题外话了。

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
