### ISSUE TITLE
startdde using 50% of CPU

### ISSUE THREAD

**Issue by cosinebob** [linuxdeepin/startdde#75]
Have seen prior threads about startdde.  Downloaded and installed version from May 20 2018.  Did not help the problem.  I have Deepin desktop installed on Ubuntu 18.04.  Just did the install last week.  One core of dual core CPU is completely taken by startdde.  Please help.  Thanks.

**Comment by cosinebob** [comment]
So, I purged deepin and went back to just basic ubuntu.  Now the system monitor shows cpu usage of less than 10% each core.  So by removing deepin I got my cpu back.

**Comment by justforlxz** [comment]
Sorry, this topic will be closed soon. If it is necessary to discuss it again, please create a new topic.
