### ISSUE TITLE
Migrate from libgnome-keyring to libsecret..

### ISSUE THREAD

**Issue by openarun** [linuxdeepin/startdde#77]
As libgnome-keyring is depreciated (not maintained anymore) and has been superseded by libsecret.

https://wiki.gnome.org/Initiatives/GnomeGoals/LibsecretMigration

**Comment by xmuli** [comment]
@justforlxz see :cat2:

**Comment by openarun** [comment]
Hi @xmuli @justforlxz @electricface.
Do we have update on this ?
Thanks !

**Comment by openarun** [comment]
Related with github.com/linuxdeepin/dpa-ext-gnomekeyring/issues/1

**Comment by ppphp** [comment]
I found it was solved by the commit 22420cdd33033b0a49a9fbc0f33cc3a7f13315d9
