### ISSUE TITLE
锁屏界面设置背景无效

### ISSUE THREAD

**Issue by wecli** [linuxdeepin/startdde#84]
系统：arch+dde
操作：进入系统设置锁屏背景，锁定屏幕。
预期结果：可以正常显示锁屏指定的背景图片
实际结果：整个锁屏界面都是白色的，无法显示锁屏背景图片。整个屏幕背景都时白色的，关机、切换用户、注销等操作按钮很难定位。
![618691455](https://user-images.githubusercontent.com/42332005/99161766-661ca980-2730-11eb-9fee-788dfcf18e81.jpg)

**Comment by hillwoodroc** [comment]
Comfirm this bug on openSUSE leap.

**Comment by wecli** [comment]
升级deepin-session-shell后问题已解决，问题不是出在startdde包而是出自dde-session-shell包
