### ISSUE TITLE
[startdde崩溃] 新装deepin20.2在小米笔记本上无法登录

### ISSUE THREAD

**Issue by meilihao** [linuxdeepin/startdde#92]
现象：在登录界面输入密码后，过几秒重新变成登录界面。

.xsession-errors里有startdde的崩溃记录, [deepin bbs帖子位置](https://bbs.deepin.org/zh/post/219156).

ps: 20.1能正常登录。

![1618842310977](https://user-images.githubusercontent.com/4382586/115252527-2ac44380-a0f1-11eb-8858-801c4ba80617.jpg)

**Comment by Vigilans** [comment]
碰到了一样的问题。根据index out of range的报错显示，是ScreenConfig中的Monitor数量出了问题：
https://github.com/linuxdeepin/startdde/blob/290fe9eafb5bd9b9230c6a2e3346070230455ccb/display/config_v4.go#L86-L93

在`result[idx] = monitor`一行里，idx超出了限制。而根据上文，`sc.OnlyOne`配置是从JSON配置文件里读的。

于是去`$HOME/.config/deepin/startdde`里，发现了`display.json`，将其删除，就可以成功登录了。

登录后再去startdde文件夹下看看，多了个`display_v5.json`。既然出错的代码在`config_v4.go`里面，看来deepin并没有做好从v4到v5的过渡……服了

**Comment by meilihao** [comment]
都两个月了, 一直没人跟进, 自从今年4月升级升坏系统后我不想再折腾, 直接切换到Ubuntu 20.04了,  因此没法验证了.
