### ISSUE TITLE
desktop文件的部分属性在DDE不起作用 (dde-*)

### ISSUE THREAD

**Issue by foresee-io** [linuxdeepin/startdde#94]
## 缺陷描述

desktop文件内有“OnlyShowIn”“NotShowIn”等属性，
但DDE启动时似乎会忽略它们。
下面将举具体例子。**仅供举例**。

## 复现步骤

1. 创建"~/.config/autostart/sample.desktop"，文件内容为
```
[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=仅在Xfce运行
Exec=deepin-app-store
OnlyShowIn=XFCE;
StartupNotify=false
Terminal=false
Hidden=false
```
2. 为该文件加可执行权限
3. 注销当前用户的会话，再进入DDE对应会话
4. _“应用商店”界面弹出，不符预期_

## 期望行为

dde会话能正确读取`OnlyShowIn`。

上述例子意为：仅当启动Xfce会话时，才运行`deepin-app-store`。
本会话非Xfce，所以**dde不该运行本命令**。

### 发行版以及版本

deepin 20 社区版，在2020-8-7保持最新

### 相关的软件包版本

dde 版本号为2020.07.30

**Comment by foresee-io** [comment]
最新的`dde`已经支持`OnlyShowIn`等属性了，`dde`对应的`XDG_CURRENT_DESKTOP=Deepin`。现关闭此issue。

**Comment by BLumia** [comment]
- 备注关联： https://github.com/linuxdeepin/developer-center/issues/3829

现在从网络上检索 deepin 的 `XDG_CURRENT_DESKTOP` 可能搜到这个 issue 所以备注到这里。`XDG_CURRENT_DESKTOP` 在 v23 起从原本的 `Deepin` 调整成 `DDE` 了。对于需要同时支持 v20 与 v23 的应用，考虑将 `OnlyShowIn` 写成 `Deepin;DDE`。若不需要考虑支持旧版本，直接写成 `DDE` 即可。
